version: "3.9"
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:noura@db:5432/Project_Tools3
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: noura
      POSTGRES_DB: Project_Tools3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
